### ISSUE TITLE
Package for Windows?

### ISSUE THREAD

**Issue by paugier** [conda-forge/pythran-feedstock#10]
It should be possible to have a conda package for Windows. 

Why do you use `skip: true  # [win]` ?

I use Pythran on Windows with Visual Studio without any problems. It should work fine on conda-forge, isn't it ?

**Comment by saraedum** [comment]
I forget what were the problems on Windows but feel free to give it a try. Just create a Pull Request that removes that line and we'll see what happens and can try to fix any issues that arise.

**Comment by serge-sans-paille** [comment]
On Thu, Apr 18, 2019 at 01:04:36AM -0700, Pierre Augier wrote:
> It should be possible to have a conda package for Windows.
> 
> Why do you use skip: true # [win] ?
> 
> I use Pythran on Windows with Visual Studio without any problems. It should
> work fine on conda-forge, isn't it ?

at least on Python3, yes. I should give it a try!

**Comment by SylvainCorlay** [comment]
It seems that this issue can be closed now!

**Comment by SylvainCorlay** [comment]
(now that the pythran feedstock builds succesfully on windows)
