### ISSUE TITLE
Make xsimd an external dependency

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/pythran-feedstock#14]
Would it be possible to make pythran depend on the conda package for xsimd instead of vendoring it in the codebase.

One means to do this could be to add a new flag to disable the vendoring in the setup.py for pythran. Thoughts?

**Comment by serge-sans-paille** [comment]
Sounds like a good idea!

**Comment by serge-sans-paille** [comment]
Fixed by #15 - note that we don't depend on the most recent version of xsimd though, to match the vendored version.

**Comment by SylvainCorlay** [comment]
Do you want to give a looser dependency requirement eventually?

**Comment by serge-sans-paille** [comment]
Probably not, that way I'm 100% sure that the conda version is same as the one
tested with travis. But as I upgraded xsimd version on pythran/master, we should
use latest version of xsimd in next release.
